version: '0.3.0.{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
  PATH: "%PYTHON%;%PYTHON%\\scripts;%PATH%"
  IPRIR_DEBUG: 1

install:
  # We need wheel installed to build wheels
  - pip install wheel
  - pip install -r requirements_ci.txt
  - python setup.py sdist bdist_wheel
  - python setup.py install --record record.txt
  # make sure database is installed
  - grep -P 'iprir\.sqlite$' record.txt
  - grep -P 'apnic\.txt$' record.txt

build: off

test_script:
  - bash ci.sh

artifacts:
  - path: 'dist\*'
