language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

env:
  - IPRIR_DEBUG=1

# command to install dependencies
install:
  - pip install -r requirements_ci.txt
  - python setup.py install --record record.txt
  # make sure database is installed
  - grep -P 'iprir\.sqlite$' record.txt
  - grep -P 'apnic\.txt$' record.txt

# command to run tests
script:
  - bash ci.sh
