language: python
python:
  - "3.2"
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

env:
  - IPRIR_DEBUG=1

# command to install dependencies
install:
  - pip install pytest-sugar
  - pip install pytest-cov
  - pip install codecov
  - python setup.py install --record record.txt && grep -P 'apnic\.sqlite$' record.txt

# command to run tests
script:
  # test installed package
  mkdir -p tmp/ && cd tmp/
  && pytest -s --verbose --cov=iprir --pyargs iprir.tests
  && cp .coverage ../ && cd ..
  && codecov
