language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

env:
  - IPRIR_DEBUG=1

# command to install dependencies
install:
  - pip install pytest-sugar
  - pip install pytest-cov
  - pip install codecov
  - python setup.py install --record record.txt
    && grep -P 'iprir\.sqlite$' record.txt
    && grep -P 'apnic\.txt$' record.txt

# command to run tests
script:
  - mkdir -p tmp/
  - cd tmp/   # test installed package
    && pytest -sv --cov=iprir --pyargs iprir.tests
    && cp .coverage ../ && cd ..
  - pytest -sv README.rst   # test README
  - codecov
